### ISSUE TITLE
Missing tags since 1.999813

### ISSUE THREAD

**Issue by atoomic** [pjacklam/p5-Math-BigInt#2]
As seen here https://github.com/pjacklam/p5-Math-BigInt/tags
the last tag available is 1.999813, we are already at 1.999828

Having tags is convenient to use GitHub UI to perform some quick compare for example or even from the command line.

Unfortunately I do not have permission to create these tags, I will gladly help and provide them if needed.

Thanks for considering creating these tags

**Comment by pjacklam** [comment]
Thanks for notifying me. I have pushed the tags now.
