### ISSUE TITLE
Pull Requests are still open on the parent repo

### ISSUE THREAD

**Issue by atoomic** [pjacklam/p5-Math-BigInt#3]
Since this repo is now the official one, or at least the advertised one on MetaCPAN

Note that two PRs are pending from
https://github.com/rafl/Math-BigInt/pulls

I'm unsure about their state, if they are already merged here or not.

it would be good to close future PR to the parent repo, and point them here instead.

**Comment by pjacklam** [comment]
I have closed the pull requests. They have been included in Math-BigInt.

**Comment by atoomic** [comment]
excellent thanks
